# ASSIGNMENT-5

Classify the email using the binary classification method. Email Spam detection has two states: 
a) Normal State – Not Spam, b) Abnormal State – Spam. 
<br>Use K-Nearest Neighbors and Support Vector Machine for classification. Analyze their performance.
<br>Dataset link: https://www.kaggle.com/datasets/balaka18/email-spam-classification-dataset-csv

In [81]:
import pandas as pd
import numpy as np

In [82]:
df= pd.read_csv('emails.csv')

In [83]:
df.dtypes

Email No.     object
the            int64
to             int64
ect            int64
and            int64
               ...  
military       int64
allowing       int64
ff             int64
dry            int64
Prediction     int64
Length: 3002, dtype: object

In [84]:
df.head()

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  jay  \
0   Email 1    0   0    1    0    0   0    2    0    0  ...         0    0   
1   Email 2    8  13   24    6    6   2  102    1   27  ...         0    0   
2   Email 3    0   0    1    0    0   0    8    0    0  ...         0    0   
3   Email 4    0   5   22    0    5   1   51    2   10  ...         0    0   
4   Email 5    7   6   17    1    5   2   57    0    9  ...         0    0   

   valued  lay  infrastructure  military  allowing  ff  dry  Prediction  
0       0    0               0         0         0   0    0           0  
1       0    0               0         0         0   1    0           0  
2       0    0               0         0         0   0    0           0  
3       0    0               0         0         0   0    0           0  
4       0    0               0         0         0   1    0           0  

[5 rows x 3002 columns]

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5172 entries, 0 to 5171
Columns: 3002 entries, Email No. to Prediction
dtypes: int64(3001), object(1)
memory usage: 118.5+ MB


In [86]:
# Check for null values
df.isnull().values.any()

False

In [87]:
df.describe()

the           to          ect          and          for  \
count  5172.000000  5172.000000  5172.000000  5172.000000  5172.000000   
mean      6.640565     6.188128     5.143852     3.075599     3.124710   
std      11.745009     9.534576    14.101142     6.045970     4.680522   
min       0.000000     0.000000     1.000000     0.000000     0.000000   
25%       0.000000     1.000000     1.000000     0.000000     1.000000   
50%       3.000000     3.000000     1.000000     1.000000     2.000000   
75%       8.000000     7.000000     4.000000     3.000000     4.000000   
max     210.000000   132.000000   344.000000    89.000000    47.000000   

                of            a          you          hou           in  ...  \
count  5172.000000  5172.000000  5172.000000  5172.000000  5172.000000  ...   
mean      2.627030    55.517401     2.466551     2.024362    10.600155  ...   
std       6.229845    87.574172     4.314444     6.967878    19.281892  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000    12.000000     0.000000     0.000000     1.000000  ...   
50%       1.000000    28.000000     1.000000     0.000000     5.000000  ...   
75%       2.000000    62.250000     3.000000     1.000000    12.000000  ...   
max      77.000000  1898.000000    70.000000   167.000000   223.000000  ...   

          connevey          jay       valued          lay  infrastructure  \
count  5172.000000  5172.000000  5172.000000  5172.000000     5172.000000   
mean      0.005027     0.012568     0.010634     0.098028        0.004254   
std       0.105788     0.199682     0.116693     0.569532        0.096252   
min       0.000000     0.000000     0.000000     0.000000        0.000000   
25%       0.000000     0.000000     0.000000     0.000000        0.000000   
50%       0.000000     0.000000     0.000000     0.000000        0.000000   
75%       0.000000     0.000000     0.000000     0.000000        0.000000   
max       4.000000     7.000000     2.000000    12.000000        3.000000   

          military     allowing           ff          dry   Prediction  
count  5172.000000  5172.000000  5172.000000  5172.000000  5172.000000  
mean      0.006574     0.004060     0.914733     0.006961     0.290023  
std       0.138908     0.072145     2.780203     0.098086     0.453817  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     1.000000     0.000000     1.000000  
max       4.000000     3.000000   114.000000     4.000000     1.000000  

[8 rows x 3001 columns]

In [88]:
import seaborn as sns
import matplotlib.pyplot as plt

In [60]:
x = df.iloc[:,1:3001]
x.shape
x

the  to  ect  and  for  of    a  you  hou  in  ...  enhancements  \
0       0   0    1    0    0   0    2    0    0   0  ...             0   
1       8  13   24    6    6   2  102    1   27  18  ...             0   
2       0   0    1    0    0   0    8    0    0   4  ...             0   
3       0   5   22    0    5   1   51    2   10   1  ...             0   
4       7   6   17    1    5   2   57    0    9   3  ...             0   
...   ...  ..  ...  ...  ...  ..  ...  ...  ...  ..  ...           ...   
5167    2   2    2    3    0   0   32    0    0   5  ...             0   
5168   35  27   11    2    6   5  151    4    3  23  ...             0   
5169    0   0    1    1    0   0   11    0    0   1  ...             0   
5170    2   7    1    0    2   1   28    2    0   8  ...             0   
5171   22  24    5    1    6   5  148    8    2  23  ...             0   

      connevey  jay  valued  lay  infrastructure  military  allowing  ff  dry  
0            0    0       0    0               0         0         0   0    0  
1            0    0       0    0               0         0         0   1    0  
2            0    0       0    0               0         0         0   0    0  
3            0    0       0    0               0         0         0   0    0  
4            0    0       0    0               0         0         0   1    0  
...        ...  ...     ...  ...             ...       ...       ...  ..  ...  
5167         0    0       0    0               0         0         0   0    0  
5168         0    0       0    0               0         0         0   1    0  
5169         0    0       0    0               0         0         0   0    0  
5170         0    0       0    0               0         0         0   1    0  
5171         0    0       0    0               0         0         0   0    0  

[5172 rows x 3000 columns]

In [61]:
y = df.iloc[:,-1].values
y.shape
y

array([0, 0, 0, ..., 1, 1, 0], dtype=int64)

In [62]:
from sklearn.model_selection import train_test_split

In [63]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 1)
x_train.shape, x_test.shape

((4137, 3000), (1035, 3000))

In [64]:
print("The shape of X_train is:",x_train.shape)

print("The shape of X_test is:",x_test.shape)

print("The shape of y_train is:",y_train.shape)

print("The shape of y_test is:",y_test.shape)

The shape of X_train is: (4137, 3000)
The shape of X_test is: (1035, 3000)
The shape of y_train is: (4137,)
The shape of y_test is: (1035,)


In [65]:
#importing packages
from sklearn.metrics import accuracy_score
import itertools
import sklearn.metrics as metrics
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay

In [66]:
# Creating holders to store the model performance results
ML_Model = []
accuracy = []
precision = []
recall=[]
f1_score=[]


#function to call for storing the results
def storeResults(model, a,b,c,d):
  ML_Model.append(model)
  accuracy.append(round(a, 3))
  precision.append(round(b, 3))
  recall.append(round(c, 3))
  f1_score.append(round(d, 3))

## SUPPORT VECTOR MACHINE

In [67]:
#Support vector machine model
from sklearn.svm import SVC

# instantiate the model
svm = SVC(kernel='linear', C=1.0, random_state=12)
#fit the model
svm.fit(x_train, y_train)

SVC(kernel='linear', random_state=12)

In [68]:
#predicting the target value from the model for the samples
y_test_svm = svm.predict(x_test)
y_train_svm = svm.predict(x_train)

### CONFUSION MATRIX

In [69]:
confusion_matrix_svm = confusion_matrix(y_test, y_test_svm)
print("Confusion Matrix - SVM")
print(confusion_matrix_svm)

Confusion Matrix - SVM
[[693  26]
 [ 25 291]]


### CLASSIFICATION REPORT

In [70]:
classification_report_svm = classification_report(y_test, y_test_svm)
print("Classification Report - SVM")
print(classification_report_svm)

Classification Report - SVM
              precision    recall  f1-score   support

           0       0.97      0.96      0.96       719
           1       0.92      0.92      0.92       316

    accuracy                           0.95      1035
   macro avg       0.94      0.94      0.94      1035
weighted avg       0.95      0.95      0.95      1035



### METRICS

In [71]:
tn, fp, fn, tp = confusion_matrix(y_test, y_test_svm).ravel()

accuracy_model  =(tp+tn)/(tp+tn+fp+fn)
precision_score =(tp)/(tp+fp)
recall_score  =(tp)/(tp+fn)
f1 =2*(( precision_score * recall_score)/( precision_score + recall_score))

### STORING RESULTS

In [72]:
storeResults('SVM',accuracy_model,precision_score,recall_score,f1)

## KNN

In [73]:
from sklearn.neighbors import KNeighborsClassifier  
knn= KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2 )  
knn.fit(x_train, y_train)

KNeighborsClassifier()

In [74]:
#predicting the target value from the model for the samples
y_test_knn = knn.predict(x_test)
y_train_knn = knn.predict(x_train)

### CONFUSION MATRIX

In [75]:
confusion_matrix_knn = confusion_matrix(y_test, y_test_knn)
print("Confusion Matrix - KNN")
print(confusion_matrix_knn)

Confusion Matrix - KNN
[[631  88]
 [ 52 264]]


### CLASSIFICATION REPORT

In [76]:
classification_report_knn = classification_report(y_test, y_test_knn)
print("Classification Report - KNN")
print(classification_report_knn)

Classification Report - KNN
              precision    recall  f1-score   support

           0       0.92      0.88      0.90       719
           1       0.75      0.84      0.79       316

    accuracy                           0.86      1035
   macro avg       0.84      0.86      0.85      1035
weighted avg       0.87      0.86      0.87      1035



### METRICS

In [77]:
tn, fp, fn, tp = confusion_matrix(y_test, y_test_knn).ravel()

accuracy_model  =(tp+tn)/(tp+tn+fp+fn)
precision_score =(tp)/(tp+fp)
recall_score  =(tp)/(tp+fn)
f1 =2*(( precision_score * recall_score)/( precision_score + recall_score))

### STORING RESULTS

In [78]:
storeResults('KNN',accuracy_model,precision_score,recall_score,f1)

## SHOWING RESULTS AND COMPAIRING

In [79]:
#creating dataframe
results = pd.DataFrame({ 'ML Model': ML_Model,    
    'Accuracy': accuracy,
    'Precision': precision,
    'Recall': recall,
    'F1-Score': f1_score})
results

ML Model  Accuracy  Precision  Recall  F1-Score
0      SVM     0.951      0.918   0.921     0.919
1      KNN     0.865      0.750   0.835     0.790

In [80]:
#Sorting the datafram on accuracy
results.sort_values(by=['Accuracy', 'Precision'], ascending=False)

ML Model  Accuracy  Precision  Recall  F1-Score
0      SVM     0.951      0.918   0.921     0.919
1      KNN     0.865      0.750   0.835     0.790